# Generated by Django 4.2.3 on 2023-08-04 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitios', '0003_rename_nombre_director_sitio_nombre_encargado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitio',
            old_name='nombre_encargado',
            new_name='nombre_director',
        ),
    ]
