# Generated by Django 4.2.3 on 2023-08-04 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitios', '0004_rename_nombre_encargado_sitio_nombre_director'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitio',
            old_name='nombre_director',
            new_name='nombre_encargado',
        ),
    ]
